// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    churn_top: {
        name: "churn_top";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          account_name: string;
          /** @sqlType STRING */
          segment: string;
          /** @sqlType DOUBLE */
          churn_score: number;
          /** @sqlType BIGINT */
          complaint_count: number;
          /** @sqlType BIGINT */
          nps: number;
        }>;
      };
    margin_trend: {
        name: "margin_trend";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          month: string;
          /** @sqlType DOUBLE */
          margin_pct: number;
        }>;
      };
    otif_trend: {
        name: "otif_trend";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          month: string;
          /** @sqlType DOUBLE */
          otif_pct: number;
        }>;
      };
  }
}
